Building DAG of jobs...
Updating job 0 (run_after_checkpoint).
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	875	removeExon
	1	run_after_checkpoint
	876

[Fri May 15 15:58:54 2020]
rule removeExon:
    input: data/annotations/ENSG00000182670.gtf
    output: data/annotationsLessExon/ENSG00000182670.gtf
    jobid: 120
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000182670

[Fri May 15 15:58:54 2020]
rule removeExon:
    input: data/annotations/ENSG00000215386.gtf
    output: data/annotationsLessExon/ENSG00000215386.gtf
    jobid: 257
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000215386

[Fri May 15 15:58:54 2020]
rule removeExon:
    input: data/annotations/ENSG00000205726.gtf
    output: data/annotationsLessExon/ENSG00000205726.gtf
    jobid: 286
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000205726

[Fri May 15 15:58:54 2020]
rule removeExon:
    input: data/annotations/ENSG00000160191.gtf
    output: data/annotationsLessExon/ENSG00000160191.gtf
    jobid: 412
    wildcards: ann=data/annotationsLessExon, gene=ENSG00000160191

[Fri May 15 15:58:54 2020]
Error in rule removeExon:
    jobid: 257
    output: data/annotationsLessExon/ENSG00000215386.gtf

[Fri May 15 15:58:54 2020]
Error in rule removeExon:
    jobid: 286
[Fri May 15 15:58:54 2020]
    output: data/annotationsLessExon/ENSG00000205726.gtf
Error in rule removeExon:

    jobid: 412
    output: data/annotationsLessExon/ENSG00000160191.gtf

[Fri May 15 15:58:54 2020]
Error in rule removeExon:
    jobid: 120
RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpb1lv5fyo.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    output: data/annotationsLessExon/ENSG00000182670.gtf
RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpl74bp9p6.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run

RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmpbmh1rud_.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
RuleException:
CalledProcessError in line 143 of /home/dlcgold/stage-unimib/extra/snake/Snakefile:
Command 'set -euo pipefail;  /usr/bin/python /home/dlcgold/stage-unimib/extra/snake/.snakemake/scripts/tmp3q93g7lh.removeExon.py' returned non-zero exit status 1.
  File "/home/dlcgold/stage-unimib/extra/snake/Snakefile", line 143, in __rule_removeExon
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/dlcgold/stage-unimib/extra/snake/.snakemake/log/2020-05-15T155854.089923.snakemake.log
